<?php
    
    $config_file_default    = "config.default";    
    $config_file_directory  = "../protected/config/";
    $config_file_name       = "main.php";    
    $config_file_path       = $config_file_directory.$config_file_name;
    
    $application_name       = "ApPHP EasyInstaller";
    $application_start_file = "index.php";
    
    $license_agreement_page = "";
    
    $sql_dump               = "db_dump.sql";
    
?>
